extends Node
## Defines all talisman effect hooks. Each talisman has an effect_id
## that maps to a set of hook callables returned by get_hooks().

## Gold generated by Copper Coin this reading
var _copper_coin_gold: int = 0
## Track first reversed card for Mirror Shard
var _mirror_shard_used: bool = false


func get_hooks(effect_id: String) -> Dictionary:
	match effect_id:
		"sage_bundle":
			return {"after_reading": _sage_bundle_after}
		"rose_quartz":
			return {"on_score": _rose_quartz_score}
		"beeswax_candle":
			return {"on_chain": _beeswax_candle_chain}
		"copper_coin":
			return {
				"before_reading": _copper_coin_before,
				"on_score": _copper_coin_score,
				"after_reading": _copper_coin_after,
			}
		"dried_lavender":
			return {"on_card_place": _dried_lavender_place}
		"quartz_point":
			return {"on_score": _quartz_point_score}
		"bone_dice":
			return {"after_reading": _bone_dice_after}
		"red_thread":
			return {"on_score": _red_thread_score}
		"wooden_rune":
			return {"on_score": _wooden_rune_score}
		"obsidian_mirror":
			return {"on_score": _obsidian_mirror_score}
		"book_of_shadows":
			return {"on_score": _book_of_shadows_score}
		"mirror_shard":
			return {
				"before_reading": _mirror_shard_before,
				"on_card_place": _mirror_shard_place,
			}
		"hex_bag":
			return {"on_score": _hex_bag_score}
		"chalice":
			return {"after_reading": _chalice_after}
		"crystal_ball":
			return {}  # Passive: UI shows next 5 draw pile cards
		"black_mirror":
			return {"on_score": _black_mirror_score}
		"iron_nail":
			return {"on_score": _iron_nail_score}
	return {}


# === COMMON TALISMANS ===

func _sage_bundle_after(_all_entries: Array) -> void:
	## -1 Veil after each reading
	VeilManager.reduce_veil(1)
	EventBus.talisman_triggered.emit("sage_bundle", "Sage Bundle: Veil -1")


func _rose_quartz_score(entry: Dictionary) -> void:
	## Cups cards +3 Insight
	if entry.card_data.suit == "cups":
		entry.insight += 3
		entry.combo_bonuses.append("Rose Quartz: +3 Insight")
		EventBus.talisman_triggered.emit("rose_quartz", "Rose Quartz: Cups +3")


func _iron_nail_score(entry: Dictionary) -> void:
	## Swords cards +3 Insight
	if entry.card_data.suit == "swords":
		entry.insight += 3
		entry.combo_bonuses.append("Iron Nail: +3 Insight")
		EventBus.talisman_triggered.emit("iron_nail", "Iron Nail: Swords +3")


func _beeswax_candle_chain(chain: Dictionary) -> void:
	## Wands chains count as 1 longer
	if chain.suit == "wands":
		chain.length += 1
		# Recalculate multiplier based on new length
		match chain.length:
			2: chain.base_multiplier = 1.5
			3: chain.base_multiplier = 2.5
			4: chain.base_multiplier = 4.0
			_: chain.base_multiplier = 7.0
		EventBus.talisman_triggered.emit("beeswax_candle", "Beeswax Candle: Wands chain +1")


func _copper_coin_before() -> void:
	_copper_coin_gold = 0


func _copper_coin_score(entry: Dictionary) -> void:
	## Pentacles cards generate +2 gold each
	if entry.card_data.suit == "pentacles":
		_copper_coin_gold += 2
		entry.combo_bonuses.append("Copper Coin: +2 gold")


func _copper_coin_after(_all_entries: Array) -> void:
	if _copper_coin_gold > 0:
		GameManager.earn_gold(_copper_coin_gold)
		EventBus.talisman_triggered.emit("copper_coin", "Copper Coin: +%d gold" % _copper_coin_gold)


func _dried_lavender_place(card_data: Resource, _is_reversed: bool, _pos: int) -> void:
	## 6-numbered cards give -2 Veil instead of -1 (extra -1 on top of base)
	if card_data.card_number == 6 and not _is_reversed:
		VeilManager.reduce_veil(1)  # Extra -1 (base -1 already applied)
		EventBus.talisman_triggered.emit("dried_lavender", "Dried Lavender: extra Veil -1")


func _quartz_point_score(entry: Dictionary) -> void:
	## +2 Insight to cards in first position of any row (positions 0, 3, 6)
	if entry.has("position_index") and entry.position_index % 3 == 0:
		entry.insight += 2
		entry.combo_bonuses.append("Quartz Point: +2 Insight")
		EventBus.talisman_triggered.emit("quartz_point", "Quartz Point: +2")


func _bone_dice_after(all_entries: Array) -> void:
	## +5 Resonance on a random card each reading
	if all_entries.is_empty():
		return
	var idx: int = randi() % all_entries.size()
	all_entries[idx].resonance += 5.0
	all_entries[idx].combo_bonuses.append("Bone Dice: +5 Resonance")
	EventBus.talisman_triggered.emit("bone_dice", "Bone Dice: +5 Res to random card")


func _red_thread_score(entry: Dictionary) -> void:
	## Adjacent same-suit cards gain +2 Insight each
	## This is checked during scoring; we mark cards that have same-suit neighbors
	if entry.has("has_same_suit_neighbor") and entry.has_same_suit_neighbor:
		entry.insight += 2
		entry.combo_bonuses.append("Red Thread: +2 Insight")


func _wooden_rune_score(entry: Dictionary) -> void:
	## Court cards gain +3 Insight (card_number 11-14)
	if entry.card_data.card_number >= 11 and entry.card_data.card_number <= 14:
		entry.insight += 3
		entry.combo_bonuses.append("Wooden Rune: +3 Insight")
		EventBus.talisman_triggered.emit("wooden_rune", "Wooden Rune: Court +3")


# === UNCOMMON TALISMANS ===

func _obsidian_mirror_score(entry: Dictionary) -> void:
	## Reversed cards gain x2 Resonance (stacks with Veil bonus)
	if entry.is_reversed:
		entry.resonance *= 2.0
		entry.combo_bonuses.append("Obsidian Mirror: Reversed x2 Res")
		EventBus.talisman_triggered.emit("obsidian_mirror", "Obsidian Mirror: x2 Res")


func _book_of_shadows_score(entry: Dictionary) -> void:
	## Major Arcana cards +8 Resonance
	if entry.card_data.card_type == "major_arcana":
		entry.resonance += 8.0
		entry.combo_bonuses.append("Book of Shadows: +8 Res")
		EventBus.talisman_triggered.emit("book_of_shadows", "Book of Shadows: +8 Res")


func _mirror_shard_before() -> void:
	_mirror_shard_used = false


func _mirror_shard_place(_card_data: Resource, is_reversed: bool, _pos: int) -> void:
	## First reversed card each reading gives no Veil
	if is_reversed and not _mirror_shard_used:
		_mirror_shard_used = true
		# Undo the Veil that was just added
		var undo_amount: int = 2 if _card_data.card_type == "major_arcana" else 1
		VeilManager.reduce_veil(undo_amount)
		EventBus.talisman_triggered.emit("mirror_shard", "Mirror Shard: no Veil")


func _hex_bag_score(entry: Dictionary) -> void:
	## 5-numbered cards give +1 Veil but x2 Resonance
	if entry.card_data.card_number == 5:
		VeilManager.add_veil(1)
		entry.resonance *= 2.0
		entry.combo_bonuses.append("Hex Bag: +1 Veil, x2 Res")
		EventBus.talisman_triggered.emit("hex_bag", "Hex Bag: 5s x2 Res")


func _chalice_after(all_entries: Array) -> void:
	## If all Cups cards in spread, Cups chain Resonance x2
	var has_non_cups: bool = false
	var cups_count: int = 0
	for entry in all_entries:
		if entry.card_data.suit == "cups":
			cups_count += 1
		elif entry.card_data.suit != "major":
			has_non_cups = true

	if cups_count >= 3 and not has_non_cups:
		for entry in all_entries:
			if entry.card_data.suit == "cups":
				entry.resonance *= 2.0
				entry.combo_bonuses.append("Chalice: All Cups x2 Res")
		EventBus.talisman_triggered.emit("chalice", "Chalice: All Cups x2")


# === RARE TALISMANS ===

func _black_mirror_score(entry: Dictionary) -> void:
	## Veil 7+: all Resonance x3. Veil 4-6: x1.5
	var veil: int = VeilManager.veil_value
	if veil >= 7:
		entry.resonance *= 3.0
		entry.combo_bonuses.append("Black Mirror: Veil 7+ x3 Res")
	elif veil >= 4:
		entry.resonance *= 1.5
		entry.combo_bonuses.append("Black Mirror: Veil 4-6 x1.5 Res")
